---
title: "multivariate_correlations"
author: "Giacomo Bignardi"
date: "2023-10-10"
output: word_document
---

```{r setup, include=FALSE}
#clean working enviroment 
rm(list = ls())
wdOA = substr(
  getwd(),
  0,
  nchar(getwd())-nchar("03_outputs/report")-1
)
wdOA_Data = "01_input"
wdOA_scripts = "02_scripts"
wdOA_output = "03_outputs/processedData"
wdNOA_ImageOutput = "05_Figures"
#load phenotypic correlations 
modelComparison_Germine_tt = read.csv(sprintf("%s/%s/01_Germine_2015/13_2_AE_tt_multivariate_modelComparison.csv",wdOA,wdOA_output))
estimates_Germine_tt= read.csv(sprintf("%s/%s/01_Germine_2015/13_2_AE_tt_multivariate_CI.csv",wdOA,wdOA_output))
rArE_Germine_tt=read.csv(sprintf("%s/%s/01_Germine_2015/13_2_AE_tt_multivariate_rArE.csv",wdOA,wdOA_output))

modelComparison_Germine_eb = read.csv(sprintf("%s/%s/01_Germine_2015/13_1_AE_eb_multivariate_modelComparison.csv",wdOA,wdOA_output))
estimates_Germine_eb= read.csv(sprintf("%s/%s/01_Germine_2015/13_1_AE_eb_multivariate_CI.csv",wdOA,wdOA_output))
rArE_Germine_eb=read.csv(sprintf("%s/%s/01_Germine_2015/13_1_AE_eb_multivariate_rArE.csv",wdOA,wdOA_output))

modelComparison_Sutherland_tt = read.csv(sprintf("%s/%s/02_Sutherland_2020/21_AE_tt_multivariate_Sutherland2020_modelComparison.csv",wdOA,wdOA_output))
modelComparison_Sutherland_eb = read.csv(sprintf("%s/%s/02_Sutherland_2020/20_AE_eb_multivariate_Sutherland2020_modelComparison.csv",wdOA,wdOA_output))
```

## Multivariate CTD model shows shared and distinct genetic influences on inter-individual differences in aesthetic value across visual domains.(part2)

To partition covariation across visual domains into genetic and environmental sources, we applied the multivariate CTD (see Methods). This method exploits MZ and DZ cross-trait cross-twin correlations (e.g., the evaluation-bias for abstract images of twin 1 with the evaluation-bias for scenes of twin 2) to partition phenotypic covariance between traits into genetic and environmental covariance components. Further, the multivariate CTD makes it possible to quantify genetic and environmental correlations, which estimate the overlaps in variance components across traits. Multivariate models were specified following univariate results. There was a good fit for the multivariate model for taste-typicality data, which included A components for scenes and faces only, and a C component for abstract images (Figure 4a; Saturated vs full ACE *$χ^2$*(*Δdf*=`r modelComparison_Germine_tt[modelComparison_Germine_tt$comparison == "mulACEvc",]$diffdf[2]`) = `r round(modelComparison_Germine_tt[modelComparison_Germine_tt$comparison == "mulACEvc",]$diffLL[2],2)`, p = `r round(modelComparison_Germine_tt[modelComparison_Germine_tt$comparison == "mulACEvc",]$p[2],2)`, full ACE vs specified model, *$χ^2$*(*Δdf*=`r modelComparison_Germine_tt[modelComparison_Germine_tt$comparison == "mulAEfa",]$diffdf[2]`) = `r round(modelComparison_Germine_tt[modelComparison_Germine_tt$comparison == "mulAEfa",]$diffLL[2],2)`, p = `r round(modelComparison_Germine_tt[modelComparison_Germine_tt$comparison == "mulAEfa",]$p[2],2)`, see Methods). The final model indicated that shared genetic effects accounted for more than half of the covariation between taste-typicality across visual domains (bivariate *$h^2_{b}$* = `r round(estimates_Germine_tt[estimates_Germine_tt$rowname == "SA21",]$estimate,2)`, 95% CI [`r round(estimates_Germine_tt[estimates_Germine_tt$rowname == "SA21",]$lbound,2)`, `r round(estimates_Germine_tt[estimates_Germine_tt$rowname == "SA21",]$ubound,2)`]) and that overlapping genetic effects jointly explained variation in taste-typicality for images of scenes and faces (genetic correlation (*ρA*), *$ρA$* = `r round(rArE_Germine_tt[rArE_Germine_tt$trait == "scenes-faces" & rArE_Germine_tt$correlation == "rA", ]$estimate,2)`, 95% CI [`r round(rArE_Germine_tt[rArE_Germine_tt$trait == "scenes-faces" & rArE_Germine_tt$correlation == "rA", ]$lbound,2)`, `r round(rArE_Germine_tt[rArE_Germine_tt$trait == "scenes-faces" & rArE_Germine_tt$correlation == "rA", ]$ubound,2)`]). This pattern contrasted with overlapping unique environmental effects on inter-individual differences for taste-typicality, which were small across all visual domains (Figure 4b). 

Similarly, the AE multivariate model fit for evaluation-bias data was good (Saturated vs full *$χ^2$*(*Δdf*=`r modelComparison_Germine_eb[modelComparison_Germine_eb$comparison == "mulACEvc",]$diffdf[2]`) = `r round(modelComparison_Germine_eb[modelComparison_Germine_eb$comparison == "mulACEvc",]$diffLL[2],2)`, p = `r round(modelComparison_Germine_eb[modelComparison_Germine_eb$comparison == "mulACEvc",]$p[2],2)`, full ACE vs specified model, *$χ^2$*(*Δdf*=`r modelComparison_Germine_eb[modelComparison_Germine_eb$comparison == "mulAEvc",]$diffdf[2]`) = `r round(modelComparison_Germine_eb[modelComparison_Germine_eb$comparison == "mulAEvc",]$diffLL[2],2)`, p = `r round(modelComparison_Germine_eb[modelComparison_Germine_eb$comparison == "mulAEvc",]$p[2],2)`). Bivariate heritability estimates spanned from bivariate *$h^2_{b}$* = `r round(estimates_Germine_eb[estimates_Germine_eb$rowname == "SA31",]$estimate,2)`, 95% CI [`r round(estimates_Germine_eb[estimates_Germine_eb$rowname == "SA31",]$lbound,2)`, `r round(estimates_Germine_eb[estimates_Germine_eb$rowname == "SA31",]$ubound,2)`], between abstract images and scenes, to bivariate *$h^2_{b}$* = `r round(estimates_Germine_eb[estimates_Germine_eb$rowname == "SA32",]$estimate,2)`, 95% CI [`r round(estimates_Germine_eb[estimates_Germine_eb$rowname == "SA32",]$lbound,2)`, `r round(estimates_Germine_eb[estimates_Germine_eb$rowname == "SA32",]$ubound,2)`], between abstract images and faces. Genetic correlations were moderate, ranging from *$ρA$* = `r round(rArE_Germine_eb[rArE_Germine_eb$trait == "scenes-faces" & rArE_Germine_eb$correlation == "rA", ]$estimate,2)`, 95% CI [`r round(rArE_Germine_eb[rArE_Germine_eb$trait == "scenes-faces" & rArE_Germine_eb$correlation == "rA", ]$lbound,2)`, `r round(rArE_Germine_eb[rArE_Germine_eb$trait == "scenes-faces" & rArE_Germine_eb$correlation == "rA", ]$ubound,2)`], between scenes and faces, to *$ρA$* = `r round(rArE_Germine_eb[rArE_Germine_eb$trait == "scenes-abstracts" & rArE_Germine_eb$correlation == "rA", ]$estimate,2)`, 95% CI [`r round(rArE_Germine_eb[rArE_Germine_eb$trait == "scenes-abstracts" & rArE_Germine_eb$correlation == "rA", ]$lbound,2)`, `r round(rArE_Germine_eb[rArE_Germine_eb$trait == "scenes-abstracts" & rArE_Germine_eb$correlation == "rA", ]$ubound,2)`], between abstract images and scenes, respectively. Unlike for taste-typicality, we also found environmental correlations to be substantial (Figure 4b). 

Findings from the validation sample (Figure 4c) were consistent with the results from the discovery sample reported above. In particular, the multivariate AE model for the taste-typicality data for scenes and faces, specified in the discovery sample, resulted in a good fit for the data in the validation sample (Saturated vs full *$χ^2$*(*Δdf*=`r modelComparison_Sutherland_tt[modelComparison_Sutherland_tt$comparison == "mulACEvc",]$diffdf[2]`) = `r round(modelComparison_Sutherland_tt[modelComparison_Sutherland_tt$comparison == "mulACEvc",]$diffLL[2],2)`, p = `r round(modelComparison_Sutherland_tt[modelComparison_Sutherland_tt$comparison == "mulACEvc",]$p[2],2)`, full ACE vs specified model, *$χ^2$*(*Δdf*=`r modelComparison_Sutherland_tt[modelComparison_Sutherland_tt$comparison == "mulAEvc",]$diffdf[2]`) = `r round(modelComparison_Sutherland_tt[modelComparison_Sutherland_tt$comparison == "mulAEvc",]$diffLL[2],2)`, p = `r round(modelComparison_Sutherland_tt[modelComparison_Sutherland_tt$comparison == "mulAEvc",]$p[2],2)`). Similarly, an AE multivariate model was a good fit for the evaluation-bias data in the validation sample (Saturated vs full ACE *$χ^2$*(*Δdf*=`r modelComparison_Sutherland_eb[modelComparison_Sutherland_eb$comparison == "mulACEvc",]$diffdf[2]`) = `r round(modelComparison_Sutherland_eb[modelComparison_Sutherland_eb$comparison == "mulACEvc",]$diffLL[2],2)`, p = `r round(modelComparison_Sutherland_eb[modelComparison_Sutherland_eb$comparison == "mulACEvc",]$p[2],2)`, full ACE vs specified model, *$χ^2$*(*Δdf*=`r modelComparison_Sutherland_eb[modelComparison_Sutherland_eb$comparison == "mulAEvc",]$diffdf[2]`) = `r round(modelComparison_Sutherland_eb[modelComparison_Sutherland_eb$comparison == "mulAEvc",]$diffLL[2],2)`, p = `r round(modelComparison_Sutherland_eb[modelComparison_Sutherland_eb$comparison == "mulAEvc",]$p[2],2)`).

